### ISSUE TITLE
Valid card numbers should have a reasonable first digit

### ISSUE THREAD

**Issue by carlansley** [checkdigit/eslint-plugin#27]
e.g. "000445575279994" should not be considered a card number, despite the fact it passes a Luhn check.

**Comment by carlansley** [comment]
@bobwieler what digits should we ignore?  0-2 and 7-9?

**Comment by ramaghanta** [comment]
didn't Mastercard introduce 2-series bins a few years ago?

**Comment by bobwieler** [comment]
correct. bins starting with 2 are now possible. 0-1 and 7-9 seem right.
